-module(openapi_condition_set_read).

-export([encode/1]).

-export_type([openapi_condition_set_read/0]).

-type openapi_condition_set_read() ::
    #{ 'key' := binary(),
       'type' => openapi_condition_set_type:openapi_condition_set_type(),
       'autogenerated' => boolean(),
       'resource_id' => openapi_resource_id:openapi_resource_id(),
       'id' := openapi_u_uid:openapi_u_uid(),
       'organization_id' := openapi_u_uid:openapi_u_uid(),
       'project_id' := openapi_u_uid:openapi_u_uid(),
       'environment_id' := openapi_u_uid:openapi_u_uid(),
       'created_at' := openapi_date_time:openapi_date_time(),
       'updated_at' := openapi_date_time:openapi_date_time(),
       'resource' => openapi_resource_read:openapi_resource_read(),
       'name' := binary(),
       'description' => binary(),
       'conditions' => maps:map()
     }.

encode(#{ 'key' := Key,
          'type' := Type,
          'autogenerated' := Autogenerated,
          'resource_id' := ResourceId,
          'id' := Id,
          'organization_id' := OrganizationId,
          'project_id' := ProjectId,
          'environment_id' := EnvironmentId,
          'created_at' := CreatedAt,
          'updated_at' := UpdatedAt,
          'resource' := Resource,
          'name' := Name,
          'description' := Description,
          'conditions' := Conditions
        }) ->
    #{ 'key' => Key,
       'type' => Type,
       'autogenerated' => Autogenerated,
       'resource_id' => ResourceId,
       'id' => Id,
       'organization_id' => OrganizationId,
       'project_id' => ProjectId,
       'environment_id' => EnvironmentId,
       'created_at' => CreatedAt,
       'updated_at' => UpdatedAt,
       'resource' => Resource,
       'name' => Name,
       'description' => Description,
       'conditions' => Conditions
     }.
