-module(openapi_condition_set_create).

-export([encode/1]).

-export_type([openapi_condition_set_create/0]).

-type openapi_condition_set_create() ::
    #{ 'key' := binary(),
       'type' => openapi_condition_set_type:openapi_condition_set_type(),
       'autogenerated' => boolean(),
       'resource_id' => openapi_resource_id:openapi_resource_id(),
       'name' := binary(),
       'description' => binary(),
       'conditions' => maps:map()
     }.

encode(#{ 'key' := Key,
          'type' := Type,
          'autogenerated' := Autogenerated,
          'resource_id' := ResourceId,
          'name' := Name,
          'description' := Description,
          'conditions' := Conditions
        }) ->
    #{ 'key' => Key,
       'type' => Type,
       'autogenerated' => Autogenerated,
       'resource_id' => ResourceId,
       'name' => Name,
       'description' => Description,
       'conditions' => Conditions
     }.
